name = "Kenna Lavender"
license = "MIT"
licenselink = "https://github.com/kewbish/kenna"
homepage = "https://kewbish.github.io/kenna"
min_version = "0.41"

[author]
  name = "Kewbish"
  homepage = "https://kewbish.github.io"
