baseURL = "/"
languageCode = "en-us"
title = "Kenna - A Hugo + NetlifyCMS boilerplate for teachers."
theme = "kenna-lavender"
relativeURLs = true
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
