backend:
  name: git-gateway
  branch: gh-pages
  repo: kenna/kewbish.github.io
  site_domain: octopus-cat-123456.netlify.com
media_folder: static/img
public_folder: /img
collections:
  - name: 'Kenna'
    label: 'Kenna'
    folder: 'content/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'publishdate', widget: 'datetime' }
      - { label: 'Due Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }