backend:
  name: github
  repo: kewbish/kenna
media_folder: static/img
collections:
  - name: 'Kenna'
    label: 'Kenna'
    folder: 'content/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'publishdate', widget: 'datetime' }
      - { label: 'Due Date', name: 'date', widget: 'datetime' }
      - { label: 'Class', name: class, widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }